name: "Deployment"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: dev
        required: true
      stage:
        type: string
        default: dev
        required: true
      github_environment:
        type: string
        required: true
      working_directory:
        type: string
        required: true
      node_version:
        type: string
        required: true
    secrets:
      awsAccount:
        required: true
      runner_token:
        required: true

jobs:
  deploy:
    name: CDK Deploy
    env:
      STAGE: ${{ inputs.stage }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Print Parameters
        run: |
          echo "environment:         ${{ inputs.environment }}"
          echo "stage:               ${{ inputs.stage }}"
          echo "github_environment:  ${{ inputs.stage }}"
          echo "working_directory:   ${{ inputs.working_directory }}"
          echo "node_version:        ${{ inputs.node_version }}"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
          registry-url: "https://npm.pkg.github.com/"
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.awsAccount}}:role/github-actions-cdk-dev-ops
          role-session-name: GithubActionsCdk${{ inputs.stage }}
          aws-region: eu-central-1

      - name: Deploy infrastructure
        working-directory: ${{ inputs.working_directory }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.runner_token }}
        run: |
          npm ci
          npx dotenv -e ../service/.env -- npm run cdk:deploy-without-approval
